### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by AlphaSystemsPL** [chemerisuk/cordova-plugin-web-share#12]
Hi,
You need to change android/WebSharePlugin.java 42 line to

`SHARE_REQUEST_CODE + 1, new Intent(Intent.EXTRA_CHOSEN_COMPONENT), PendingIntent.FLAG_CANCEL_CURRENT | PendingIntent.FLAG_MUTABLE);`

for android 12 support

**Comment by fredriksthlm** [comment]
@chemerisuk . This change is important. The plugin doesn't work at all in the current state for API31+
But this small addition from @VVilquack fixes it.

**Comment by chemerisuk** [comment]
@VVilquack do you mind to create a PR with the requested change?

**Comment by chemerisuk** [comment]
Fixed in v1.2.1. Please let me know if it works for you @VVilquack @fredriksthlm

**Comment by AlphaSystemsPL** [comment]
Everything worked for me on iOS and Android API 31
