### ISSUE TITLE
cordova-support-android-plugin - wrong version. Fail on install

### ISSUE THREAD

**Issue by fredriksthlm** [chemerisuk/cordova-plugin-web-share#14]
This plugin cannot be installed if I also install your other plugins (before).

`Failed to install 'cordova-plugin-web-share': CordovaError: Version of installed plugin: "cordova-support-android-plugin@2.0.4" does not satisfy dependency plugin requirement "cordova-support-android-plugin@~1.0.0". Try --force to use installed plugin as dependency.`

Since you have updated your support-plugin which gets installed by the other plugins, while this plugin uses the old version, which is hard coded.
some of your plugins have the support plugin hardcoded to 2.0.4, 2.0.3 and 1.0.0...

Can you please verify this dependency for _all_ your plugins, otherwise they cannot be installed togheter. (or fully remove the version code)

**Comment by chemerisuk** [comment]
Hi @fredriksthlm . I’m aware and plan to update this plugin soon

**Comment by chemerisuk** [comment]
Released v1.3.0 that uses latest version of `cordova-support-android-plugin`
