### ISSUE TITLE
On Android If quickly to tap share button many times, many sharesheet windows open at the same time

### ISSUE THREAD

**Issue by supermaximus80** [chemerisuk/cordova-plugin-web-share#17]
On Android If quickly to tap share button many times, many sharesheet windows open at the same time.
How to prevent multiple sharesheet windows opening or multiple buttons clicking?

**Comment by chemerisuk** [comment]
I believe you can introduce a flag that will set to true as soon as share method is called and check if it’s false before calling share.

**Comment by supermaximus80** [comment]
@chemerisuk 

This helped me to solve the problem. Thanks.
