### ISSUE TITLE
text mandatory for sharing

### ISSUE THREAD

**Issue by phal0r** [chemerisuk/cordova-plugin-web-share#2]
Hi @chemerisuk ,

thanks for this plugin. Was exactly what I was looking after. One remark: You are writing in the docs, that all options for sharing are optional, but text is mandatory (at least for android).  So should it be optional or should the docs be changed?

**Comment by chemerisuk** [comment]
@phal0r I believe you can share just a url without any text, right?

**Comment by phal0r** [comment]
@chemerisuk 
No, at least not with 1.1.0, but I saw you have released 1.2.0 and changed some stuff in the share method. For me 1.2.0 is not working:
```
Installing "cordova-plugin-web-share" for android
Failed to install 'cordova-plugin-web-share': Error: Expected plugin to have ID "cordova-support-android-plugin" but got "cordova-plugin-web-share".
```

**Comment by chemerisuk** [comment]
@phal0r weird. can you post full install log with a command you use?

**Comment by phal0r** [comment]
@chemerisuk 
Will try to set it up again with 1.2.0
